CREATE TABLE `customer` (
    `id` bigint(24) NOT NULL AUTO_INCREMENT,
    `cif_code` varchar(30) NOT NULL UNIQUE,
    `level` bigint(24) NOT NULL,
    `type` bigint(24) NOT NULL,
    `title` varchar(10) NULL,
    `full_name` varchar(100) NOT NULL,
    `mothers_maiden` varchar(50) NOT NULL,
    `gender` varchar(10) NOT NULL,
    `birth_date` datetime NOT NULL,
    `email` varchar(100) DEFAULT NULL,
    `status` bigint(24) NOT NULL,
    `created_date` datetime NOT NULL,
    `created_by` varchar(30) NOT NULL,
    `last_updated_date` datetime DEFAULT NULL,
    `last_updated_by` varchar(30) DEFAULT NULL,
    `company_code` varchar(30) DEFAULT NULL,
    `employers_code` varchar(20) DEFAULT NULL,
    `profile_version` varchar(10) DEFAULT NULL,
    `cif_code_nkyc` varchar(30) DEFAULT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY FKCUSTOMERLEVEL(`level`) REFERENCES lookup(`id`),
    FOREIGN KEY FKCUSTOMERTYPE(`type`) REFERENCES lookup(`id`),
    FOREIGN KEY FKCUSTOMERSTATUS(`status`) REFERENCES status(`id`)
)