// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID              int64          `json:"id"`
	CifCode         string         `json:"cif_code"`
	Level           int64          `json:"level"`
	Type            int64          `json:"type"`
	Title           sql.NullString `json:"title"`
	FullName        string         `json:"full_name"`
	MothersMaiden   string         `json:"mothers_maiden"`
	Gender          string         `json:"gender"`
	BirthDate       time.Time      `json:"birth_date"`
	Email           sql.NullString `json:"email"`
	Status          int64          `json:"status"`
	CreatedDate     time.Time      `json:"created_date"`
	CreatedBy       string         `json:"created_by"`
	LastUpdatedDate sql.NullTime   `json:"last_updated_date"`
	LastUpdatedBy   sql.NullString `json:"last_updated_by"`
	CompanyCode     sql.NullString `json:"company_code"`
	EmployersCode   sql.NullString `json:"employers_code"`
	ProfileVersion  sql.NullString `json:"profile_version"`
	CifCodeNkyc     sql.NullString `json:"cif_code_nkyc"`
}

type Lookup struct {
	ID          int64          `json:"id"`
	Type        string         `json:"type"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Priority    sql.NullInt32  `json:"priority"`
	Description sql.NullString `json:"description"`
	Shortname   sql.NullString `json:"shortname"`
	Status      int64          `json:"status"`
	Filter      sql.NullString `json:"filter"`
}

type Status struct {
	ID          int64          `json:"id"`
	Type        string         `json:"type"`
	Code        string         `json:"code"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}
