// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error)
	CreateLookup(ctx context.Context, arg CreateLookupParams) (sql.Result, error)
	CreateStatus(ctx context.Context, arg CreateStatusParams) (sql.Result, error)
	DeleteCustomerById(ctx context.Context, id int64) error
	DeleteLookupById(ctx context.Context, id int64) error
	DeleteStatusById(ctx context.Context, id int64) error
	GetCustomerById(ctx context.Context, id int64) (Customer, error)
	GetCustomerByIdForUpdate(ctx context.Context, id int64) (Customer, error)
	GetLookupById(ctx context.Context, id int64) (Lookup, error)
	GetLookupByIdForUpdate(ctx context.Context, id int64) (Lookup, error)
	GetStatusById(ctx context.Context, id int64) (Status, error)
	GetStatusByIdForUpdate(ctx context.Context, id int64) (Status, error)
	ListCustomer(ctx context.Context) ([]Customer, error)
	ListLookup(ctx context.Context) ([]Lookup, error)
	ListStatus(ctx context.Context) ([]Status, error)
}

var _ Querier = (*Queries)(nil)
